# Define the Docker Compose version
version: "3"

# Define the services that make up your application
services:

    # Configuration for the web service
    web:
        container_name: ${PROJECT}-web
        working_dir: /var/www
        image: ${PROJECT-web}
        build:
            context: .
            dockerfile: .docker/Web/Dockerfile
        environment:
            DB_HOST: ${PROJECT}-database
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        networks:
            - shared_network
        depends_on:
            - database
        entrypoint: /usr/local/bin/entrypoint.sh
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    # Configuration for the database service
    database:
        container_name: ${PROJECT}-database
        image: "mariadb"
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        networks:
            - shared_network

    # Configuration for the phpMyAdmin service
    phpmyadmin:
        container_name: ${PROJECT}-phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: database
            PMA_PORT: ${DB_PORT}
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - shared_network

# Define the Project's Network
networks:
    shared_network:
        driver: bridge

# Define the Project's Volumes
volumes:
    database:
        driver: local
